version: "3.8"

services:
  postgres:
    container_name: gestao_vagas_pg
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gestao_vagas
    volumes:
      - gestao_vagas_pg_data:/bitnami/postgresql

volumes:
  gestao_vagas_pg_data:
